---
abstract: 'Perl extension for accessing pachube.com'
author:
  - 'Mark Hindess <soft-pachube@temporalanomaly.com>'
build_requires:
  English: 0
  Test::More: 0
  XML::SAX: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Pachube
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  XML::Simple: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Net-Pachube
  repository: git://github.com/beanz/net-pachube-perl.git
version: 1.102900
