--- #YAML:1.0
name:                Net-Pachube
version:             0.01
abstract:            Perl extension for accessing pachube.com
license:             ~
author:              
    - Mark Hindess <soft-pachube@temporalanomaly.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0
    LWP::UserAgent:                0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
